config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :videos do
    member do
      put "like"=>"videos#like"
      put "dislike"=>"videos#dislike"
    end
  end

  mount Commontator::Engine => '/commontator'

  resources :users do
    resources :subscriptions, only: [:create]
  end

  resources :subscriptions, only: [:destroy]


  post '/playlist/add/:id', to: 'playlists#add', as: 'playlist_add'
  delete '/playlist/remove/:id', to: 'playlists#remove', as: 'playlist_remove'

  get 'user/myprofile' => 'users#myprofile'
  get 'user/user_profile/:id' => 'users#user_profile', as: 'user_user_profile'
  get 'user/subscribers' => 'users#subscribers'
  get 'user/myplaylist' => 'users#myplaylist'

  delete 'video/:id' => 'videos#destroy', as: 'video_delete'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'videos#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :videos, dependent: :destroy

  has_one_attached :profilePic, :dependent => :destroy

  acts_as_commontator

  acts_as_voter

  #def self.from_google(uid:, email:, full_name:, avatar_url:)
    #byebug
    #user = User.find_or_create_by(email: email) do |u|
      #u.uid = uid
      #u.name = full_name
      #u.profilePic = avatar_url
      #u.encrypted_password = SecureRandom.hex
    #end
    #user.update(uid: uid, name: full_name, profilePic: avatar_url)
    #byebug
  #end
  #def self.from_google(email:, full_name:, uid:, avatar_url:)
    #$geslo=Devise.friendly_token.first(20)
    #create_with(uid: uid, name: full_name, profilePic: avatar_url, password: $geslo, password_confirmation: $geslo).find_or_create_by!(email: email)
  #end

  #def self.new_with_session(params, session)
  #  super.tap do |user|
  #    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
  #      user.email = data["email"] if user.email.blank?
  #    end
  #    if data = session["devise.google_oauth2"] && session["devise.google_oauth2_data"]["extra"]["raw_info"]
  #      user.email = data["email"] if user.email.blank?
  #    end
  #  end
  #end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
      if data = session["devise.google_oauth2"] && session["devise.google_oauth2_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  #def self.from_omniauth(auth)
  #  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #    user.email = auth.info.email
  #    user.password = Devise.friendly_token[0,20]
  #    user.name = auth.info.name   # assuming the user model has a name
  #    user.profilePic = auth.info.image
  #  end
  #end

  #def self.from_omniauth(access_token)
    #where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    #  user.email = auth.info.email
    #  user.password = Devise.friendly_token[0, 20]
    #  user.name = auth.info.name
    #  user.profilePic = auth.info.image
    #end
  #  data = access_token.info
  #  user = User.where(email: data['email']).first

  #  unless user
  #       user = User.create(name: data['name'],
  #          email: data['email'],
  #          password: Devise.friendly_token[0,20],
  #          profilePic: data['image'],
  #          uid: data['uid'],
  #          provider: data['provider']
  #       )
  #  end
  #  user
  #end
  def self.from_omniauth(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = provider_data.info.name   # assuming the user model has a name
      #user.profilePic = provider_data.info.image
    end
  end

  #def self.create_from_provider_data(provider_data)
  #  where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do | user |
  #    user.email = provider_data.info.email
  #    user.password = Devise.friendly_token[0, 20]
  #    user.skip_confirmation!
  #  end
  #end

  has_many :playlists, :dependent => :destroy

  #subscriber
  has_many :subscribed_chanels, foreign_key: "subscriber_id", class_name: 'Subscription'
  #has_many :subscribers, through: :subscribed_users
  has_many :subscribers, foreign_key: "subscribed_to_id", class_name: 'Subscription'
  #has_many :subscribed_tos, through: :subscribing_users
  #has_many :subscriber_associations, :foreign_key => :subscriber_id, :class_name => 'Subscription'
  #has_many :subscribing_user_associations, :through => :subscriber_associations, :source => :subscribed_to
  #subscribed_toright
  #has_many :subscribed_to_associations, :foreign_key => :subscribed_to_id, :class_name => 'Subscription'
  #has_many :subscribing_chanel_associations, :through => :subscribed_to_associations, :source => :subscriber
  #def associations
    #(subscribing_user_associations + subscribing_chanel_associations).flatten.uniq
  #end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.google_oauth2_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def facebook
     @user = User.from_omniauth(request.env['omniauth.auth'])
     #puts @user.to_yaml
     if @user.persisted?
       sign_in_and_redirect @user
       set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
     else
       flash[:error] = 'There was a problem signing you in through Facebook. Please register or try signing in later.'
       redirect_to new_user_registration_url
     end
  end

  def failure
    flash[:error] = 'There was a problem signing you in. Please register or try signing in later.'
    redirect_to new_user_registration_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user=User.find(params[:id])
    @subscription=@user.subscribers.find_by(subscriber: current_user)
  end

  def myprofile
    @user=current_user.id
    @videos=current_user.videos
    @playlist=Playlist.all.where(user_id: current_user.id)
  end

  def subscribers
    @user=current_user.id
    #@subscriptions=Subscription.all
    #@subscrbed=User.joins("INNER JOIN subscriptions ON subscriber_id=#{current_user.id}")
    @subscrbed=Subscription.all.where(subscriber_id: current_user.id)
    @users=User.all
    #@videos=Video.all
    #@subs=@users.where(id: @subscribed.id)
  end

  def user_profile
    @user=User.find(params[:id])
    @videos=@user.videos
    @subscription=@user.subscribers.find_by(subscriber: current_user)
    @playlist=Playlist.all.where(user_id: @user.id)
    #session[:return_to] ||= request.referer
  end

  def myplaylist
    @playlist=Playlist.all.where(user_id: current_user.id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/myplaylist.html.erb
<tbody>
  <div class="container" style="Text-align:center;">
    <h3>My playlist</h3>
    <br><br>
  </div>
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% if @playlist.any? %>
        <% @playlist.each do |playlist| %>
            <% @video=Video.all.find_by(id: playlist.video_id) %>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <%#= image_tag @video.thumbnail, :class => "card-img-top", style: "width:100%; height:225px;" if @video.thumbnail.attached?%>
                <% if @video.thumbnail.attached? %>
                  <%= image_tag @video.thumbnail,  :class=>"card-img-top", :style=>"width:100%; height:225px;" %>
                <% else %>
                  <%= image_tag "blank_thumb.jpg", :class=>"card-img-top", :style=>"width:100%; height:225px;" %>
                <% end %>
                <div class="card-body">
                  <p class="card-text" style="font-size:1.3em;"><%= @video.title %></p>
                  <p class="card-text" style="font-weight:300;"><%= @video.user.name %></p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <%= link_to 'Watch', @video, :class => "btn btn-sm btn-outline-secondary" %>
                    </div>
                    <small class="text-muted"><%= time_ago_in_words(@video.created_at) %> ago</small>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
      <% else %>
        <div class="no_videos" style="width:100%; margin:0 auto; text-align:center;">
          <h4>You have no videos on your playlist.</h4
        </div>
      <% end %>
    </div>
  </div>
      <!-- <td><%#= video.description %></td>
      <td><%#= link_to 'Show', video %></td>
      <td><%#= link_to 'Edit', edit_video_path(video) %></td>
      <td><%#= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->

</tbody>

app/views/users/myprofile.html.erb
<div class="outter-container">

  <div class="container">
    <div class="main-body">

          <!-- /Breadcrumb -->

          <div class="row gutters-sm" style="height:100%;">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <% if current_user.profilePic.attached? %>
                      <%= image_tag current_user.profilePic, class: 'rounded-circle' , width: "150"%>
                    <% else %>
                      <%= image_tag "blank_profile.png", class: "rounded-circle" , width: "150" %>
                    <% end %>
                    <div class="mt-3">
                      <h4><%= current_user.name %></h4>
                      <%= current_user.subscribers.count %> Subscribers
                    </div>
                    <br><br>
                    <%= link_to "Edit my profile", edit_user_registration_path, :class=>"btn btn-outline-primary" %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">

                  <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#home" class="nav-link">Videos</a></li>
                    <li><a data-toggle="tab" href="#menu1" class="nav-link">My Playlist</a></li>
                  </ul>

                  <div class="tab-content">
                    <div id="home" class="tab-pane fade in active overflow-auto">
                      <ul class="list-group list-group-flush">
                        <% if @videos.any? %>
                          <% @videos.each do |video| %>
                            <a href="<%= video_path(video.id) %> ">
                              <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <%#= image_tag video.thumbnail, class: 'img-thumbnail h-100 w-25' if video.thumbnail.attached? %>
                                <% if video.thumbnail.attached? %>
                                  <%= image_tag video.thumbnail,  :class=>"img-thumbnail h-100 w-25", :style=>"width:100%; height:130px;" %>
                                <% else %>
                                  <%= image_tag "blank_thumb.jpg", :class=>"img-thumbnail h-100 w-25", :style=>"width:100%; height:130px;" %>
                                <% end %>
                                <p><%= video.title %></p>
                              </li>
                            </a>
                          <% end %>
                        <% else %>
                        <div class="" style="margin:0 auto;text-align:center;">
                          <br>
                          <h5>You havent uploaded any videos yet...</h5>
                        </div>
                        <% end %>
                      </ul>
                    </div>
                    <div id="menu1" class="tab-pane fade">
                      <% if @playlist.any? %>
                        <% @playlist.each do |playlist| %>
                          <% @ply=Video.all.find_by(id: playlist.video_id) %>
                          <a href="<%= video_path(@ply.id) %> ">
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                              <%#= image_tag @ply.thumbnail, class: 'img-thumbnail h-100 w-25' if @ply.thumbnail.attached? %>
                              <% if @ply.thumbnail.attached? %>
                                <%= image_tag @ply.thumbnail,  :class=>"img-thumbnail h-100 w-25", :style=>"width:100%; height:130px;" %>
                              <% else %>
                                <%= image_tag "blank_thumb.jpg", :class=>"img-thumbnail h-100 w-25", :style=>"width:100%; height:130px;" %>
                              <% end %>
                              <p><%= @ply.title %></p>
                            </li>
                          </a>
                        <% end %>
                      <% else %>
                        <div class="" style="margin:0 auto;text-align:center;">
                          <br>
                          <h5>You don't have any videos on your playlist yet...</h5>
                        </div>
                      <% end %>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
    </div>

</div>

app/views/users/subscribers.html.erb
<h3 style="text-align:center;">Subscriptions</h3><br>
<div class="users">
    <% if @subscrbed %>
      <div class="container">
        <ul class="list-group">
          <% @subscrbed.each do |subs| %>
            <% if(subs.subscriber_id=current_user.id) %>
                <li class="list-group-item" style="vertical-align: middle;">
                  <h4 style=" margin: 0 auto;"><% @uporabnik=@users.find_by(id: subs.subscribed_to_id) %>
                  <% if @uporabnik.profilePic.attached? %>
                    <%= image_tag @uporabnik.profilePic, class: "profilePIC" %>
                  <% else %>
                    <%= image_tag "blank_profile.png", class: "profilePIC" %>
                  <% end %>
                  <%= @uporabnik.name %>
                  <%= link_to "View profile", user_user_profile_path(@uporabnik.id), :class=>"btn btn-primary float-right" %></h4>
                </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    <% end %>
</div>

app/views/users/user_profile.html.erb
<div class="outter-container">

  <div class="container">
    <div class="main-body">

          <!-- /Breadcrumb -->

          <div class="row gutters-sm" style="height:100%;">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <% if @user.profilePic.attached? %>
                      <%= image_tag @user.profilePic, class: 'rounded-circle' , width: "150"%>
                    <% else %>
                      <%= image_tag "blank_profile.png", class: "rounded-circle" , width: "150" %>
                    <% end %>
                    <div class="mt-3">
                      <h4><%= @user.name %></h4>
                      <% if user_signed_in? %>
                        <% if @subscription.present? %>
                          <%= link_to "Unsubscribe", subscription_path(@subscription.id),class: 'btn btn-outline-secondary', method: :delete %>
                        <% else %>
                          <%= link_to "Subscribe", user_subscriptions_path(@user.id),class: 'btn btn-outline-secondary', method: :post %>
                        <% end %>
                      <% else %>
                        <%= link_to "Subscribe", new_user_session_path(),class: 'btn btn-outline-secondary' %>
                      <% end %>
                      <%= @user.subscribers.count %> Subscribers
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">

                  <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#home" class="nav-link">Videos</a></li>
                    <li><a data-toggle="tab" href="#menu1" class="nav-link"><%= @user.name %>'s Playlist</a></li>
                  </ul>

                  <div class="tab-content">
                    <div id="home" class="tab-pane fade in active overflow-auto">
                      <ul class="list-group list-group-flush">
                        <% if @videos.any? %>
                          <% @videos.each do |video| %>
                            <a href="<%= video_path(video.id) %> ">
                              <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <%#= image_tag video.thumbnail, class: 'img-thumbnail h-100 w-25' if video.thumbnail.attached? %>
                                <% if video.thumbnail.attached? %>
                                  <%= image_tag video.thumbnail,  :class=>"img-thumbnail h-100 w-25", :style=>"width:100%; height:130px;" %>
                                <% else %>
                                  <%= image_tag "blank_thumb.jpg", :class=>"img-thumbnail h-100 w-25", :style=>"width:100%; height:130px;" %>
                                <% end %>
                                <p><%= video.title %></p>
                              </li>
                            </a>
                          <% end %>
                        <% else %>
                          <div class="" style="margin:0 auto;text-align:center;">
                            <br>
                            <h5>User hasn't uploaded any videos yet...</h5>
                          </div>
                        <% end %>
                      </ul>
                    </div>
                    <div id="menu1" class="tab-pane fade">
                      <% if @playlist.any? %>
                        <% @playlist.each do |playlist| %>
                          <% @ply=Video.all.find_by(id: playlist.video_id) %>
                          <a href="<%= video_path(@ply.id) %> ">
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                              <%#= image_tag @ply.thumbnail, class: 'img-thumbnail h-100 w-25' if @ply.thumbnail.attached? %>
                              <% if @ply.thumbnail.attached? %>
                                <%= image_tag @ply.thumbnail,  :class=>"img-thumbnail h-100 w-25", :style=>"width:100%; height:130px;" %>
                              <% else %>
                                <%= image_tag "blank_thumb.jpg", :class=>"img-thumbnail h-100 w-25", :style=>"width:100%; height:130px;" %>
                              <% end %>
                              <p><%= @ply.title %></p>
                            </li>
                          </a>
                        <% end %>
                      <% else %>
                        <div class="" style="margin:0 auto;text-align:center;">
                          <br>
                          <h5><%= @user.name %> doesn't have any videos on his/hers playlist yet...</h5>
                        </div>
                      <% end %>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
    </div>

</div>