config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :videos do
    member do
      put "like"=>"videos#like"
      put "dislike"=>"videos#dislike"
    end
  end

  mount Commontator::Engine => '/commontator'

  resources :users do
    resources :subscriptions, only: [:create]
  end

  resources :subscriptions, only: [:destroy]


  post '/playlist/add/:id', to: 'playlists#add', as: 'playlist_add'
  delete '/playlist/remove/:id', to: 'playlists#remove', as: 'playlist_remove'

  get 'user/myprofile' => 'users#myprofile'
  get 'user/user_profile/:id' => 'users#user_profile', as: 'user_user_profile'
  get 'user/subscribers' => 'users#subscribers'
  get 'user/myplaylist' => 'users#myplaylist'

  delete 'video/:id' => 'videos#destroy', as: 'video_delete'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'videos#index'
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  has_many :playlists, :dependent => :destroy

  def self.search(search)
    if search
      where(["lower(title) LIKE lower(?)","%#{search}%"])
    else
      Video.all
    end
  end

  mount_uploader :video, VideoUploader

  has_one_attached :thumbnail, :dependent => :destroy

  acts_as_commontable dependent: :destroy

  acts_as_votable dependent: :destroy
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy, :like, :dislike]
  before_action :authenticate_user! , except: [:show, :index]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.search(params[:search])
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    commontator_thread_show(@video)
    #show subscribe
    #@user=User.find(params[:id])
    @subscription=@video.user.subscribers.find_by(subscriber: current_user)
    if user_signed_in?
      @playlist=Playlist.find_by(user_id: current_user.id, video_id: @video.id)
    end
    @rand_videos = Video.where.not(id: @video.id).order('RANDOM()').limit(4)
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @video.user=current_user

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #LIKE/DISLIKE
  #liking video
  def like
    if current_user.voted_up_on? @video
      @video.unliked_by current_user
      redirect_to video_path
    else
      @video.liked_by current_user
      redirect_to video_path
    end
  end
  #disliking video
  def dislike
    if current_user.voted_down_on? @video
      @video.undisliked_by current_user
      redirect_to video_path
    else
      @video.disliked_by current_user
      redirect_to video_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :video, :description, :thumbnail, :search)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <div class="form-signin">
              <%= form_with(model: video, local: true) do |form| %>
                <% if video.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

                    <ul>
                      <% video.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                <br>
                <div class="field form-label-group">
                  <%= form.label :title %>
                  <%= form.text_field :title, :class=>"form-control" %>
                </div>
                <br>
                <div class="field form-label-group">
                  <%= form.label :video %><br>
                  <%= form.file_field :video, id: :video_file, :class=>"form-control" %>
                </div>
                <br>
                <div class="field form-label-group">
                  <%= form.label :thumbnail %><br>
                  <% if video.thumbnail.attached? %>
                    <%= image_tag video.thumbnail, style: "width: 200px;" %>
                  <% end %>

                  <%= form.file_field :thumbnail, :class=>"form-control" %>
                </div>
                <br>
                <div class="field form-label-group">
                  <%= form.label :description %>
                  <%= form.text_area :description, :class=>"form-control" %>
                </div>
                <br>
                <div class="actions form-label-group">
                  <%= form.submit "Upload video", :class=>"btn btn-lg btn-primary btn-block text-uppercase" %>
                </div>
                <br>
                <%= link_to "Cancel", root_path, :class=>"btn btn-outline-danger btn-block text-uppercase" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/videos/edit.html.erb
<div class="" style="margin:0 auto;">
  <h4 style="margin:0 auto;text-align:center;">Edit video</h4>
</div>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
  <tbody>

    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <% @videos.each do |video| %>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <%#= image_tag video.thumbnail, :class => "card-img-top", style: "width:100%; height:225px;" if video.thumbnail.attached?%>
                <% if video.thumbnail.attached? %>
                  <%= image_tag video.thumbnail,  :class=>"card-img-top", :style=>"border:0.5px solid black;width:100%; height:225px;" %>
                <% else %>
                  <%= image_tag "blank_thumb.jpg", :class=>"img-fluid", :style=>"border:0.5px solid black;width:100%; height:225px;" %>
                <% end %>
                <div class="card-body">
                  <p class="card-text" style="font-size:1.3em;"><%= video.title %></p>
                  <p class="card-text" style="font-weight:300;">
                    <% if video.user.profilePic.attached? %>
                      <%= image_tag video.user.profilePic, :class=>"profileIMG" %>
                    <% else %>
                      <%= image_tag "blank_profile.png", :class=>"profileIMG" %>
                    <% end %>
                    <%= link_to video.user.name, user_user_profile_path(video.user.id), :style=>"color:black;decorations:none;" %></p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <%= link_to 'Watch', video, :class => "btn btn-sm btn-outline-secondary" %>
                    </div>
                    <small class="text-muted"><%= time_ago_in_words(video.created_at) %> ago</small>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
      </div>
    </div>
        <!-- <td><%#= video.description %></td>
        <td><%#= link_to 'Show', video %></td>
        <td><%#= link_to 'Edit', edit_video_path(video) %></td>
        <td><%#= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->

  </tbody>

app/views/videos/new.html.erb
<div class="" style="margin:0 auto;">
  <h4 style="margin:0 auto;text-align:center;">Upload new video</h4>
</div>
<%= render 'form', video: @video %>

<%#= link_to '< Back', videos_path %>

app/views/videos/show.html.erb
<div class="container">

  <!-- Portfolio Item Row -->
  <div class="row">

    <div class="col-md-8">
      <div class="embed-responsive embed-responsive-16by9">
         <iframe class="embed-responsive-item" src="<%= @video.video %>" allowfullscreen></iframe>
      </div>
    </div>

    <div class="col-md-4">
      <h1 class="my-4">
        <small><%= @video.title %></small>
      </h1>
      <h5>
        <% if @video.user.profilePic.attached? %>
          <%= image_tag @video.user.profilePic, :class=>"profileIMG" %>
        <% else %>
          <%= image_tag "blank_profile.png", :class=>"profileIMG" %>
        <% end %>
        <%= link_to @video.user.name, user_user_profile_path(@video.user.id), :style=>"color:black;decorations:none;" %>
      </h5>
      <%= user_subscribe %>
<hr>
      <h4 class="my-3">Description</h4>
      <p><%= @video.description %></p>
      Uploaded at: <%= @video.created_at.to_time.strftime('%d. %m. %Y at %l:%m') %>
      <br><br>
      <div class="like">
        <%= like_dislike %>
      </div>
      <br>
      <% if user_signed_in? %>
        <% if @playlist.present? %>
          <%= link_to "Remove from my playlist", playlist_remove_path(@video.id),class: 'btn btn-outline-secondary', method: :delete %>
        <% else %>
          <%= link_to "Add to my playlist", playlist_add_path(@video.id),class: 'btn btn-outline-secondary', method: :post %>
        <% end %>
      <% else %>
        <%= link_to "Add to my playlist", new_user_session_path, class: 'btn btn-outline-secondary' %>
      <% end %>

    </div>

  </div>
  <!-- /.row -->
<br><br>
<hr>
  <!-- Related Projects Row -->
  <h3 class="my-4">Other videos</h3>

  <div class="row">

      <% @rand_videos.each do |video| %>

      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <a href="<% video_path(video.id) %>" style="color:black;decoration:none;">
                  <% if video.thumbnail.attached? %>
                    <%= image_tag video.thumbnail,  :class=>"img-fluid", :style=>"border:0.5px solid black;width:224px;height:126px;" %>
                  <% else %>
                    <%= image_tag "blank_thumb.jpg", :class=>"img-fluid", :style=>"border:0.5px solid black;width:224px;height:126px;" %>
                  <% end %>
                  <h5><%= video.title %></h5>
            </a>
            <h6>
              <%= link_to video.user.name, user_path(video.user.id) %></h6>

          </div>
        </div>
      </div>
      <% end %>
  </div>
  <!-- /.row -->
  <hr>

  <div class="row">
    <%= commontator_thread(@video) %>
  </div>
  <br>
  <%= link_to '< Back', videos_path %>
  <% if user_signed_in? %>
    <% if current_user.id==@video.user.id %>
      <%= link_to ' Edit ', edit_video_path(@video) %>
      <%= link_to ' Delete ', video_delete_path(@video.id), method: :delete %>
    <% end %>
  <% end %>
</div>
<!-- /.container -->